name: Publish to Docker
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Add your test steps here if needed...
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: ewin2k
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ewin2k/publish-packages/game
          tag_with_sha: true
